-- Seed the exercise catalogue.
--
-- Reference data, so it lives in a migration rather than a script: it is
-- versioned with the schema that shapes it, it goes through review like any
-- other change, and any fresh database replays it automatically.
--
-- It CANNOT be done from the app with the anon key — `exercises` has no INSERT
-- policy, deliberately. That is RLS working, not an obstacle to route around.
--
-- Ids are generated by Postgres. The 'ex-01' strings in the old mock array were
-- only ever placeholders for the mock; real rows get real uuids.

insert into exercises (name, muscle_group, equipment, video_url) values
  ('Barbell Bench Press', 'chest', 'barbell', '/videos/bench-press.mp4'),
  ('Incline Dumbbell Press', 'chest', 'dumbbell', null),
  ('Cable Chest Fly', 'chest', 'cable', null),
  ('Push-Up', 'chest', 'bodyweight', '/videos/push-up.mp4'),
  ('Barbell Deadlift', 'back', 'barbell', null),
  ('Lat Pulldown', 'back', 'machine', null),
  ('Seated Cable Row', 'back', 'cable', null),
  ('Pull-Up', 'back', 'bodyweight', null),
  ('Overhead Press', 'shoulders', 'barbell', null),
  ('Dumbbell Lateral Raise', 'shoulders', 'dumbbell', null),
  ('Reverse Pec Deck Fly', 'shoulders', 'machine', null),
  ('Dumbbell Biceps Curl', 'arms', 'dumbbell', null),
  ('Cable Triceps Pushdown', 'arms', 'cable', null),
  ('Barbell Back Squat', 'legs', 'barbell', null),
  ('Leg Press', 'legs', 'machine', null),
  ('Bulgarian Split Squat With Rear Foot Elevated on Bench', 'legs', 'bodyweight', null),
  ('Plank', 'core', 'bodyweight', null),
  ('Hanging Leg Raise', 'core', 'bodyweight', null),
  ('Cable Woodchopper', 'core', 'cable', null);
